regions:
  - ap-northeast-2
  - us-east-1
  - eu-west-1
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-3
  - me-central-1
  - us-west-2

account-blocklist:
  - "337909764629" # Management Account
  - "246705294232" # Custom-Customer-Resources
  - "062484260092" # CleverTap SaaS Platform

resource-types:
  excludes:
    - S3Object # Excluded because S3 bucket removal handles removing all S3Objects
    - ServiceCatalogTagOption # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - ServiceCatalogTagOptionPortfolioAttachment # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - FMSNotificationChannel # Excluded because it's not available
    - FMSPolicy # Excluded because it's not available
    - MachineLearningMLModel # Excluded due to ML being unavailable
    - MachineLearningDataSource # Excluded due to ML being unavailable
    - MachineLearningBranchPrediction # Excluded due to ML being unavailable
    - MachineLearningEvaluation # Excluded due to ML being unavailable
    - RoboMakerDeploymentJob # Deprecated Service
    - RoboMakerFleet # Deprecated Service
    - RoboMakerRobot # Deprecated Service
    - RoboMakerSimulationJob
    - OSPackage
    - RoboMakerRobotApplication
    - RoboMakerSimulationApplication
    - OpsWorksApp # Deprecated service
    - OpsWorksInstance # Deprecated service
    - OpsWorksLayer # Deprecated service
    - OpsWorksUserProfile # Deprecated service
    - OpsWorksCMBackup # Deprecated service
    - OpsWorksCMServer # Deprecated service
    - OpsWorksCMServerState # Deprecated service
    - CodeStarProject # Deprecated service
    - CodeStarConnection # Deprecated service
    - CodeStarNotification # Deprecated service
    - Cloud9Environment # Deprecated service
    - CloudSearchDomain # Deprecated service
    - RedshiftServerlessSnapshot # Deprecated service
    - RedshiftServerlessNamespace # Deprecated service
    - RedshiftServerlessWorkgroup # Deprecated service
    - AWS::Timestream::ScheduledQuery # Deprecated service
    - ElasticTranscoderPipeline # Deprecated service


presets:
  organization:
    filters:
      IAMSAMLProvider:
        - property: ARN
          type: contains
          value: "AWSSSO"
      IAMRole:
        - property: Name
          type: contains
          value: "OrganizationAccountAccessRole"
      IAMRolePolicyAttachment:
        - property: RoleName
          value: "OrganizationAccountAccessRole"
  
  controltower:
    filters:
      ConfigServiceConfigurationRecorder:
        - property: Name
          value: "aws-controltower-BaselineConfigRecorder"
      ConfigServiceDeliveryChannel:
        - property: Name
          value: "aws-controltower-BaselineConfigDeliveryChannel"
      CloudTrailTrail:
        - property: Name
          type: contains
          value: "aws-controltower-"
      CloudWatchLogsLogGroup:
        - property: logGroupName
          type: contains
          value: "/aws/lambda/aws-controltower-"
      CloudWatchEventsRule:
        - property: Name
          value: "aws-controltower-ConfigComplianceChangeEventRule"
      CloudWatchEventsTarget:
        - property: Rule
          value: "aws-controltower-ConfigComplianceChangeEventRule"
        - property: TargetID
          value: "Compliance-Change-Topic"
      SNSTopic:
        - property: TopicARN
          type: contains
          value: ":aws-controltower-SecurityNotifications"
      SNSSubscription:
        - property: ARN
          type: contains
          value: ":aws-controltower-SecurityNotifications"
      LambdaFunction:
        - property: Name
          type: contains
          value: "aws-controltower-"
      SecretsManagerSecret:
        - property: ARN
          type: contains
          value: "aws-controltower-"
        - property: ARN
          type: contains
          value: "events!connection"

  defaults:
    filters:
      EC2Subnet:
        - property: DefaultVPC
          value: "true"
      EC2DefaultSecurityGroupRule:
        - property: DefaultVPC
          value: "true"
      EC2DHCPOption:
        - property: DefaultVPC
          value: "true"
      EC2VPC:
        - property: IsDefault
          value: "true"
      EC2InternetGateway:
        - property: DefaultVPC
          value: "true"
      EC2InternetGatewayAttachment:
        - property: DefaultVPC
          value: "true"

accounts:
  'AWS_ACCOUNT_ID_PLACEHOLDER':
    presets:
      - organization
      - defaults
      - controltower