version: 2.1
orbs:
  python: circleci/python@2.1.0
jobs:
  deploy-image:
    machine:
      image: ubuntu-2204:current

    steps:
    
      - checkout

      - run:
          name: "Deploy"
          command: |
            pip install cfstack tabulate
            python execute.py 


workflows:
  deploy-image: 
    jobs:
      - deploy-image