version: 2.1
jobs:
  deploy-image:
    machine:
      image: ubuntu-2204:current

    steps:
      - run:
          name: "Install Pre-requisites"
          command: |
            sudo su
            apt-get update
            apt-get install -y pip3 
                      
      - checkout

      - run:
          name: "Deploy"
          command: |
            pip3 install cfstack tabulate
            python3 execute.py 


workflows:
  deploy-image: 
    jobs:
      - deploy-image