version: 2.1
jobs:
  deploy-image:
    machine:
      image: ubuntu-2204:current

    steps:
      - run:
          name: "Install Pre-requisites"
          command: |
            sudo apt-get install software-properties-common
            sudo apt-add-repository universe
            sudo apt-get update
            sudo apt-get install python-pip

      - checkout

      - run:
          name: "Deploy"
          command: |
            pip3 install cfstack tabulate
            python3 execute.py 


workflows:
  deploy-image: 
    jobs:
      - deploy-image