name: AWS Nuke Account

run-name: AWS Nuke - ${{ inputs.AWS_ACCOUNT_ID }}-${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      AWS_ACCOUNT_ID:
        type: string
        description: AWS Account ID to nuke
        required: true
      AWS_ACCESS_KEY_ID:
        type: string
        description: AWS Access Key ID (will be masked)
        required: true
      AWS_SECRET_ACCESS_KEY:
        type: string
        description: AWS Secret Access Key (will be masked)
        required: true

env:
  AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      caller-account: ${{ steps.verify.outputs.caller-account }}
      caller-user: ${{ steps.verify.outputs.caller-user }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Mask Credentials
        run: |
          AWS_ACCESS_KEY_ID=$(jq -r '.inputs.AWS_ACCESS_KEY_ID' $GITHUB_EVENT_PATH)
          AWS_SECRET_ACCESS_KEY=$(jq -r '.inputs.AWS_SECRET_ACCESS_KEY' $GITHUB_EVENT_PATH)
          echo ::add-mask::$AWS_ACCESS_KEY_ID
          echo ::add-mask::$AWS_SECRET_ACCESS_KEY
          echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> $GITHUB_ENV
          echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> $GITHUB_ENV

      - name: Verify AWS Creds for the account to be nuked
        id: verify
        run: |
          aws sts get-caller-identity
          CALLER_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
          CALLER_USER=$(aws sts get-caller-identity --query Arn --output text)
          echo "caller-account=$CALLER_ACCOUNT" >> $GITHUB_OUTPUT
          echo "caller-user=$CALLER_USER" >> $GITHUB_OUTPUT
          if [ "$CALLER_ACCOUNT" != "${{ inputs.AWS_ACCOUNT_ID }}" ]; then
            echo "ERROR: Credentials are for account $CALLER_ACCOUNT, but you specified ${{ inputs.AWS_ACCOUNT_ID }}"
            exit 1
          fi
          echo "AWS credentials verified for account $CALLER_ACCOUNT"
          echo "AWS User: $CALLER_USER"

  approval:
    runs-on: ubuntu-latest
    needs: validate
    environment: wait-for-approval
    steps:
      - name: Manual Approval Required
        run: |
          echo "Account ID: ${{ inputs.AWS_ACCOUNT_ID }}"
          echo "AWS User: ${{ needs.validate.outputs.caller-user }}"
          echo "Please review the account ID and AWS user above and confirm you want to proceed with nuking this account."
         
  execute:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    needs: [validate, approval]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download AWS Nuke Tool
        run: |
          wget -c https://github.com/rebuy-de/aws-nuke/releases/download/v2.25.0/aws-nuke-v2.25.0-linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local/bin
          sudo mv /usr/local/bin/aws-nuke-v2.25.0-linux-amd64 /usr/local/bin/aws-nuke
          sudo chmod +x /usr/local/bin/aws-nuke
          aws-nuke version

      - name: Mask Credentials
        run: |
          AWS_ACCESS_KEY_ID=$(jq -r '.inputs.AWS_ACCESS_KEY_ID' $GITHUB_EVENT_PATH)
          AWS_SECRET_ACCESS_KEY=$(jq -r '.inputs.AWS_SECRET_ACCESS_KEY' $GITHUB_EVENT_PATH)
          echo ::add-mask::$AWS_ACCESS_KEY_ID
          echo ::add-mask::$AWS_SECRET_ACCESS_KEY
          echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> $GITHUB_ENV
          echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> $GITHUB_ENV
  
      - name: Install yq
        run: |
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x /usr/local/bin/yq
          yq --version

      - name: Update Config File with Account ID
        run: |
          ACCOUNT_ID="${{ inputs.AWS_ACCOUNT_ID }}"
          yq eval "with(.accounts; .[\"$ACCOUNT_ID\"] = .[\"AWS_ACCOUNT_ID_PLACEHOLDER\"] | del(.[\"AWS_ACCOUNT_ID_PLACEHOLDER\"]))" aws-nuke-config.yaml -i
          echo "Config file updated for account ${{ inputs.AWS_ACCOUNT_ID }}"
        
      - name: Execute AWS Nuke
        run: |
          echo "EXECUTING AWS NUKE"
          echo "Account: ${{ inputs.AWS_ACCOUNT_ID }}"
          echo "AWS User: ${{ needs.validate.outputs.caller-user }}"
          echo "Timestamp: $(date)"
          
          aws-nuke \
            --config aws-nuke-config.yaml \
            --access-key-id ${AWS_ACCESS_KEY_ID} --secret-access-key ${AWS_SECRET_ACCESS_KEY} \
            --no-dry-run \
            --force
          
          echo "AWS Nuke execution completed"
