name: ECS Force Deploy Service

run-name: ECS Force Deploy - ${{ inputs.ECS_CLUSTER_NAME }}/${{ inputs.ECS_SERVICE_NAME }}-${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      AWS_REGION:
        type: choice
        description: AWS Region
        required: true
        default: 'eu-west-1'
        options:
          - us-east-1
          - us-west-2
          - eu-west-1
          - ap-southeast-1
          - ap-south-1
          - me-central-1
          - ap-southeast-3
          - ap-northeast-2
      ECS_CLUSTER_NAME:
        type: choice
        description: ECS Cluster Name
        required: true
        default: 'eu1-Poller-Staging-Service-PollerEcsCluster99E29D7C-5IzLxVko7Rjp'
        options:
          - eu1-Poller-Staging-Service-PollerEcsCluster99E29D7C-5IzLxVko7Rjp
          - in1-Poller-Staging-Service-PollerEcsCluster99E29D7C-s2sVxWJM2f3a
          - Semaphore-Ecs-s1-Agent-SemaphoreAgentEcsCluster-9tUYfq9pQPj5

      ECS_SERVICE_NAME:
        type: choice
        description: ECS Service Name
        required: true
        default: 'eu1-Poller-Staging-Service-PollerEcsService2FA3C4F1-UA6uSIvc4zOG'
        options:
          - eu1-Poller-Staging-Service-PollerEcsService2FA3C4F1-UA6uSIvc4zOG
          - in1-Poller-Staging-Service-PollerEcsService2FA3C4F1-8rjUiMXqybC7
          - Semaphore-Ecs-s1-Agent-Service
env:
  AWS_REGION: ${{ inputs.AWS_REGION }}
  ECS_CLUSTER_NAME: ${{ inputs.ECS_CLUSTER_NAME }}
  ECS_SERVICE_NAME: ${{ inputs.ECS_SERVICE_NAME }}

jobs:
  force-deploy-ecs-service:
    runs-on: eu1
    timeout-minutes: 60
    
    steps:
      - name: Checkout Infra-Actions Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: |
          echo "Installing Python dependencies..."
          python3 -m pip install --upgrade pip --user
          python3 -m pip install boto3 botocore --user
          
      - name: Details of the deployment
        run: |
          
          echo "Deploying ECS service with following configuration:"
          echo "Region: $AWS_REGION"
          echo "Cluster: $ECS_CLUSTER_NAME"
          echo "Service: $ECS_SERVICE_NAME"

      - name: Verify AWS CLI
        run: |
          # Verify AWS CLI is available
          aws --version

      - name: Check ECS Service Exists
        run: |
          echo "Checking if ECS service exists..."
          SERVICE_COUNT=$(aws ecs describe-services \
            --cluster "$ECS_CLUSTER_NAME" \
            --services "$ECS_SERVICE_NAME" \
            --region "$AWS_REGION" \
            --query 'length(services)' \
            --output text)
          
          if [ "$SERVICE_COUNT" -eq 0 ]; then
            echo "ERROR: ECS service '$ECS_SERVICE_NAME' not found in cluster '$ECS_CLUSTER_NAME'"
            exit 1
          fi
          
          SERVICE_STATUS=$(aws ecs describe-services \
            --cluster "$ECS_CLUSTER_NAME" \
            --services "$ECS_SERVICE_NAME" \
            --region "$AWS_REGION" \
            --query 'services[0].status' \
            --output text)
          
          echo "ECS service exists and is accessible (Status: $SERVICE_STATUS)"

      - name: Get Current Service Configuration
        id: get-current-config
        run: |
          echo "Getting current service configuration..."
          CURRENT_TASK_DEFINITION=$(aws ecs describe-services \
            --cluster "$ECS_CLUSTER_NAME" \
            --services "$ECS_SERVICE_NAME" \
            --region "$AWS_REGION" \
            --query 'services[0].taskDefinition' \
            --output text)
          
          echo "Current task definition: $CURRENT_TASK_DEFINITION"
          echo "CURRENT_TASK_DEFINITION=$CURRENT_TASK_DEFINITION" >> $GITHUB_OUTPUT

      - name: Force New Deployment
        run: |
          echo "Forcing new deployment..."
          aws ecs update-service \
            --cluster "$ECS_CLUSTER_NAME" \
            --service "$ECS_SERVICE_NAME" \
            --task-definition "${{ steps.get-current-config.outputs.CURRENT_TASK_DEFINITION }}" \
            --force-new-deployment \
            --region "$AWS_REGION"
          
          echo "Deployment initiated successfully!"

      - name: Wait for Deployment to Complete
        run: |
          echo "Waiting for deployment to complete..."
          aws ecs wait services-stable \
            --cluster "$ECS_CLUSTER_NAME" \
            --services "$ECS_SERVICE_NAME" \
            --region "$AWS_REGION"
          
          echo "Deployment completed successfully!"

      - name: Get Final Deployment Status
        run: |
          echo "Final deployment status:"
          aws ecs describe-services \
            --cluster "$ECS_CLUSTER_NAME" \
            --services "$ECS_SERVICE_NAME" \
            --region "$AWS_REGION" \
            --query 'services[0].deployments[0].[status,desiredCount,runningCount,pendingCount,failedTasks]' \
            --output table

      - name: Deployment Summary
        if: always()
        run: |
          echo "=== Deployment Summary ==="
          echo "Region: $AWS_REGION"
          echo "Cluster: $ECS_CLUSTER_NAME"
          echo "Service: $ECS_SERVICE_NAME"
          
          # Get final service status
          aws ecs describe-services \
            --cluster "$ECS_CLUSTER_NAME" \
            --services "$ECS_SERVICE_NAME" \
            --region "$AWS_REGION" \
            --query 'services[0].[status,desiredCount,runningCount,pendingCount,failedTasks]' \
            --output table
          
          # Check for any failed tasks
          FAILED_TASKS=$(aws ecs describe-services \
            --cluster "$ECS_CLUSTER_NAME" \
            --services "$ECS_SERVICE_NAME" \
            --region "$AWS_REGION" \
            --query 'services[0].failedTasks' \
            --output text)
          
          if [[ "$FAILED_TASKS" != "0" ]]; then
            echo "WARNING: $FAILED_TASKS failed tasks detected"
            echo "DEPLOYMENT_STATUS=warning" >> $GITHUB_ENV
          else
            echo "All tasks are running successfully"
            echo "DEPLOYMENT_STATUS=success" >> $GITHUB_ENV
          fi

      - name: Create Summary Report
        if: always()
        run: |
          echo "## ECS Force Deploy Service Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployment Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- **Region:** $AWS_REGION" >> $GITHUB_STEP_SUMMARY
          echo "- **Cluster:** $ECS_CLUSTER_NAME" >> $GITHUB_STEP_SUMMARY
          echo "- **Service:** $ECS_SERVICE_NAME" >> $GITHUB_STEP_SUMMARY
          echo "- **Task Definition:** ${{ steps.get-current-config.outputs.CURRENT_TASK_DEFINITION }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Get final service status for summary
          SERVICE_STATUS=$(aws ecs describe-services \
            --cluster "$ECS_CLUSTER_NAME" \
            --services "$ECS_SERVICE_NAME" \
            --region "$AWS_REGION" \
            --query 'services[0].[status,desiredCount,runningCount,pendingCount,failedTasks]' \
            --output json)
          
          DESIRED_COUNT=$(echo "$SERVICE_STATUS" | jq -r '.[1]')
          RUNNING_COUNT=$(echo "$SERVICE_STATUS" | jq -r '.[2]')
          PENDING_COUNT=$(echo "$SERVICE_STATUS" | jq -r '.[3]')
          FAILED_TASKS=$(echo "$SERVICE_STATUS" | jq -r '.[4]')
          
          echo "### Service Status" >> $GITHUB_STEP_SUMMARY
          echo "- **Desired Count:** $DESIRED_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "- **Running Count:** $RUNNING_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "- **Pending Count:** $PENDING_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "- **Failed Tasks:** $FAILED_TASKS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [[ "$FAILED_TASKS" != "0" ]]; then
            echo "### ⚠️ Warning" >> $GITHUB_STEP_SUMMARY
            echo "Some tasks failed during deployment. Please check the ECS console for details." >> $GITHUB_STEP_SUMMARY
          else
            echo "### ✅ Success" >> $GITHUB_STEP_SUMMARY
            echo "All tasks are running successfully." >> $GITHUB_STEP_SUMMARY
          fi
